date1 = input("Введите дату: ")
task1 = input("Введите название задачи: ")
date2 = input("Введите дату: ")
task2 = input("Введите название задачи: ")
date3 = input("Введите дату: ")
task3 = input("Введите название задачи: ")
print(date1 + " " + task1)
print(date2 + " " + task2)
print(date3 + " " + task3)